### ISSUE TITLE
Missing audible.json

### ISSUE THREAD

**Issue by ahosker** [tskulbru/hearable#1]
The script is looking for audible.json, but mine is called main.json. 

I think the solution is to get the ``auth-file`` name from the from ``config.toml`` in the ``entrypoint.sh``  when its setting the ``activation_bytes``.

I'm not great at bash.

(p.s. thanks for this package)

**Comment by tskulbru** [comment]
Thanks for reporting. Yea I will need to fetch the filename from https://github.com/mkb79/audible-cli library. Probably using `audible manage profile list` which outputs a table structure. Should be doable
